#!/bin/sh

bluetoothctl connect 6C:93:08:60:71:75

setxkbmap -layout g

xmodmap ~/.Xmodmap

xset r 66

xset r rate 300 40 &

feh --no-fehbg --bg-fill '/home/penguin/Pictures/Wallpapers/THEWP.png' &

unclutter -idle 3 &

redshift -l 23.0:72.6 -t 5000:5000 -g 0.9 -m randr -v &

exec dwm
