#!/bin/sh

setxkbmap -layout g

xmodmap ~/.Xmodmap

xset r rate 250 50 r 66 &

feh --no-fehbg --bg-fill '/home/penguin/Pictures/Wallpapers/THEWP.png' &

unclutter -idle 4 &

redshift -l 23.0:72.6 -t 5000:5000 -g 0.9 -m randr -v &

exec dwm
